### ISSUE TITLE
还是没有修复composer 2.0

### ISSUE THREAD

**Issue by yuanzhihai** [top-think/think-installer#3]
核心目录没有了 thinkphp

**Comment by yzh52521** [comment]
- Downloading topthink/framework (v5.1.40)
  - Installing topthink/framework (v5.1.40): Extracting archive
 Failed to extract topthink/framework: (9) unzip -qq  '/Applications/MAMP/htdocs/thinkphp51/tp/vendor/composer/tmp-6361ff891843abd309f7e11a7505386d' -d '/Applications/MAMP/htdocs/thinkphp51/tp/vendor/composer/7333dfc5'

unzip:  cannot find or open /Applications/MAMP/htdocs/thinkphp51/tp/vendor/composer/tmp-6361ff891843abd309f7e11a7505386d.

    This most likely is due to a custom installer plugin not handling the returned Promise from the downloader
    See https://github.com/composer/installers/commit/5006d0c28730ade233a8f42ec31ac68fb1c5c9bb for an example fix
