### ISSUE TITLE
5.1.40 全新安装的时候会报错, 如下

### ISSUE THREAD

**Issue by ghostong** [top-think/think-installer#7]
`  
- Installing topthink/framework (v5.1.40): Reading /root/.composer/cache/files/topthink/framework/a29c7f647362d43a9c0a7cbf9051ef97da437c4a.zip from cache
Loading from cache
 Extracting archivePHP Fatal error:  Uncaught Error: Call to undefined function React\Promise\resolve() in /code/ucenter_backend/vendor/topthink/think-installer/src/LibraryInstaller.php:27
Stack trace:
#0 /code/ucenter_backend/vendor/topthink/think-installer/src/LibraryInstaller.php(14): think\composer\LibraryInstaller->makePromise(NULL)
#1 /code/ucenter_backend/vendor/topthink/think-installer/src/ThinkFramework.php(37): think\composer\LibraryInstaller->install(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\Package\CompletePackage))
#2 phar:///usr/bin/composer/src/Composer/Installer/InstallationManager.php(173): think\composer\ThinkFramework->install(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\Package\CompletePackage))
#3 phar:///usr/bin/composer/src/Composer/Installer/InstallationManager.php(160): Composer\Installer\InstallationManager->install(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\DependencyResolver\Operation\InstallOperation))
#4 phar:///usr/bin/co in /code/ucenter_backend/vendor/topthink/think-installer/src/LibraryInstaller.php on line 27

`

**Comment by yunwuxin** [comment]
修正了
